name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1.9.0
      with:
        dotnet-version: '5.0'
    - name: Install dependencies
      run: dotnet restore ./Advent-of-Code-2021/Advent-of-Code-2021.sln
    - name: Build
      run: dotnet build ./Advent-of-Code-2021/Advent-of-Code-2021.sln --no-restore
    - name: Test
      run: dotnet test ./Advent-of-Code-2021/Advent-of-Code-2021.sln --no-restore --verbosity normal
      
      
